# File name must be config.yaml and it can be located in the root directory
# or in the internal/config directory.

# Example configuration file for the application
server:
  host: localhost
  port: 8080

database:
  host: localhost
  port: 5432
  user: your_db_user
  password: your_db_password
  name: your_db_name
  sslmode: false