// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"database/sql"
)

type Category struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
}

type Tag struct {
	ID       int32  `json:"id"`
	Name     string `json:"name"`
	ColorHex string `json:"color_hex"`
}

type Task struct {
	ID          int32          `json:"id"`
	Name        string         `json:"name"`
	Description sql.NullString `json:"description"`
	Status      int16          `json:"status"`
	Priority    int16          `json:"priority"`
	DueDate     sql.NullTime   `json:"due_date"`
	CreatedAt   sql.NullTime   `json:"created_at"`
	UpdatedAt   sql.NullTime   `json:"updated_at"`
	UserID      int32          `json:"user_id"`
}

type TasksTag struct {
	TaskID int32 `json:"task_id"`
	TagID  int32 `json:"tag_id"`
}

type User struct {
	ID           int32        `json:"id"`
	Username     string       `json:"username"`
	Email        string       `json:"email"`
	PasswordHash string       `json:"password_hash"`
	CreatedAt    sql.NullTime `json:"created_at"`
	UpdatedAt    sql.NullTime `json:"updated_at"`
	IsActive     sql.NullBool `json:"is_active"`
}
